[project]
name = "detr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asttokens==3.0.0",
    "coloredlogs==15.0.1",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "exceptiongroup==1.2.2",
    "executing==2.2.0",
    "flatbuffers==25.2.10",
    "fonttools==4.56.0",
    "graphviz==0.20.3",
    "humanfriendly==10.0",
    "ipython==8.33.0",
    "jedi==0.19.2",
    "kiwisolver==1.4.8",
    "matplotlib==3.10.1",
    "matplotlib-inline==0.1.7",
    "mkl-service==2.4.0",
    "ml-dtypes==0.5.1",
    "onnx==1.17.0",
    "onnxruntime==1.20.1",
    "onnxscript==0.2.2",
    "packaging==24.2",
    "pandas==2.2.3",
    "parso==0.8.4",
    "pexpect==4.9.0",
    "prompt-toolkit==3.0.50",
    "protobuf==6.30.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pydot==3.0.4",
    "pygments==2.19.1",
    "pyinstrument==5.0.1",
    "pyparsing==3.2.1",
    "python-dateutil==2.9.0.post0",
    "scipy==1.15.1",
    "six==1.17.0",
    "stack-data==0.6.3",
    "torch",
    "torchvision",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "triton==3.1.0",
]

[tool.uv.sources]
torch = { url = "https://download.pytorch.org/whl/cpu/torch-2.5.1%2Bcpu-cp310-cp310-linux_x86_64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cpu/torchvision-0.20.1%2Bcpu-cp310-cp310-linux_x86_64.whl" }
